### ISSUE TITLE
"My current task"

### ISSUE THREAD

**Issue by KruciferX** [idena-network/idena-desktop#269]
Sometimes a client gives false current task that leads some users into thinking that they already sent flips and then they fail validation cause of it.

It seems that client doesn't "care" for actual status of node/address, but uses internal data to figure out if a flip has been submitted or not.

I suggest implementation of blockchain check during client startup to determine the actual state of current task.

**Comment by aidenaio** [comment]
yes, this is under investigation rn

**Comment by aidenaio** [comment]
thanks for your input 👐

**Comment by aidenaio** [comment]
fixed with https://github.com/idena-network/idena-desktop/pull/268

**Comment by KruciferX** [comment]
Apparently, this is still not solved.

![image](https://user-images.githubusercontent.com/52136297/80034959-7c8eb980-84ef-11ea-9a48-f24ec0f05b1e.png)

![image](https://user-images.githubusercontent.com/52136297/80035022-93351080-84ef-11ea-834b-25f446800a99.png)
